# Generated by Django 5.0.6 on 2024-06-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darkless', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id_ropa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('TipoRopa', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=60)),
                ('detalle', models.CharField(max_length=100)),
            ],
        ),
    ]
