# Generated by Django 5.0.6 on 2024-06-28 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Darkless', '0002_ropa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ropa2',
            fields=[
                ('id_ropa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_lazamiento', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(db_column='idTipo', primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Ropa',
        ),
        migrations.AddField(
            model_name='ropa2',
            name='id_tipo',
            field=models.ForeignKey(db_column='ISTipo', on_delete=django.db.models.deletion.CASCADE, to='Darkless.tipo'),
        ),
    ]
